[package]
name = "fectl"
version = "0.2.6"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Process management utility"
readme = "README.md"
keywords = []
homepage = "https://github.com/fafhrd91/fectl"
repository = "https://github.com/fafhrd91/fectl.git"
documentation = "https://fafhrd91.github.io/fafhrd91/fectl/"
categories = ["development-tools::ffi"]
license = "Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
build = "build.rs"

[[bin]]
name = "fectld"
path = "src/main.rs"

[[bin]]
name = "fectl"
path = "client/main.rs"

[dependencies]
libc = "0.2"
nix = "0.9"
net2 = "0.2"
byteorder = "1.1"
chrono = "0.4"
boxfnonce = "*"

# tokio
bytes = "0.4"
mio = "0.6"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-signal = "0.1"
tokio-uds = "0.1"

# logging
time = "*"
log = "0.3"
syslog = "3.2"
env_logger = "0.4"

# cli
structopt = "0.1"
structopt-derive = "0.1"

# config
toml = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"

[dependencies.actix]
version = "^0.4.2"

[profile.release]
lto = true
opt-level = 3
debug = true
